---
title: "a1_task2_walsh_shelby"
author: "Shelby Walsh"
date: "1/22/2021"
output: html_document
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE, echo = TRUE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(janitor)
library(here)
library(ggfortify)
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)
library(patchwork)
```

```{r}
world_env <- read_csv("world_env_vars.csv") %>% 
  clean_names() 

world_env_pca <- world_env %>% 
  select(cropland_cover, tree_canopy_cover, temp_mean_annual, rain_mean_annual) %>% 
  rename(Annual.Mean.Rain = rain_mean_annual,
        Cropland.Cover = cropland_cover,
         Tree.Canopy.Cover = tree_canopy_cover ,
         Annual.Mean.Temp = temp_mean_annual ) %>% 
  drop_na() %>% 
  scale() %>% 
  prcomp()

world_env_u <- world_env %>% 
  drop_na(cropland_cover, tree_canopy_cover, temp_mean_annual, rain_mean_annual) %>% 
  rename()

world_env_pca$rotation

world_pca_plot <- autoplot(world_env_pca,
         data = world_env_u,
         #shape = FALSE,
         loadings = TRUE,
         colour = "lightpink2",
         loadings.label = TRUE,
         loadings.colour = "black",
         loadings.label.colour = "black",
         loadings.label.vjust = -0.3,
         loadings.label.hjust = 1.15,
         loadings.label.size  = 4,
         loadings.label.face = "bold"
         ) +
  theme_minimal() +
  theme(legend.position = "none")


```
```{r, fig.cap= "**Figure 1. PCA biplot comparing the relationships between Cropland cover, tree canopy cover, annual mean temperature and annual mean rainfall around the world.** "}

world_pca_plot

```

## Global PCA Biplot Findings

+ Cropland cover is negatively correlated with Annual mean temperature
+ Tree Canopy Cover and Annual Mean Temperature are highly positively correlated
+ Annual mean rainfall and tree canopy cover have little correlation to cropland cover and annual mean temperatures.
