---
title: "a1_task1_walsh_shelby"
author: "Shelby Walsh"
date: "1/21/2021"
output: html_document
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE, echo = TRUE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(janitor)
library(here)
library(readxl)
library(ggplot2)
library(patchwork)
library(lubridate)
```

## Sierra Amphibian Analysis
```{r}
#read in xlsx data and clean coulmn names and species names
sierra_amp <- read_excel("sierra_amphibians.xlsx") %>% 
  clean_names() %>% 
  mutate(across(where(is.character), tolower)) 
```


```{r}
#Graph 1: Mountain yellow-legged frog counts based on life stage and year
#modify table to get counts for mountain yellow-legged frog per year grouped by life stage (excluding eggmass)
mylf <- sierra_amp %>% 
  mutate(year = year(survey_date)) %>% 
  select(amphibian_species, amphibian_life_stage, amphibian_number, year) %>% 
  filter(amphibian_species == "ramu",
         amphibian_life_stage %in% c("tadpole", "subadult", "adult")) %>% 
  group_by(year, amphibian_life_stage) %>% 
  summarise(ramu_count = sum(amphibian_number))


#create lables for facet wrap graph titles
lables <- c(adult = "Adult", subadult = "Subadult", tadpole = "Tadpole")

#create 3 facet wrapped graphs so each life stage is graphed seperately, with a free frog count scale (y scale)
graph_life <- ggplot(data = mylf, aes(x = year, y = ramu_count)) +
  geom_bar(stat = "identity", aes(fill = amphibian_life_stage, alpha = 1, width = .4), show.legend = FALSE) +
  scale_fill_brewer(palette = "YlOrRd") +
  theme_minimal()+
  facet_wrap(~amphibian_life_stage, scales = "free_y", 
             labeller = labeller(amphibian_life_stage = lables))+      
  labs(x = "",
       y = "Frogs Observed",
         title = "A") +
   theme(plot.title = element_text(size = 10,
                                   face = "bold",
        hjust = 0)) +
  theme(text = element_text(size = 10),
        axis.title.y = element_text(size = 8),
        strip.text.x = element_text(size=8, face = "bold"))

```


```{r}
# Graph 2: Mountain yellow-legged frog counts per lake from 1995-2002 in life stages subadult and adult
lakes <- sierra_amp %>% 
  select(lake_id, amphibian_species, amphibian_life_stage, amphibian_number)%>%
  filter(amphibian_species == "ramu",
         amphibian_life_stage %in% c("subadult", "adult")) %>% 
  group_by(lake_id) %>% 
  summarise(ramu_count = sum(amphibian_number))

lakes$lake_id <- paste0('Lake ', lakes$lake_id, sep = ' ')

#factor reorder to get largest to smallest number of frogs, only keep the top 5 lakes
top_5_lakes <- lakes %>% 
  top_n(5) %>% 
  mutate(lake_id = fct_reorder(lake_id, ramu_count)) 

#plot frogs from top 5 lakes largest to smallest, flip coords so when graphs combine, easier to read all 4 
 graph_lakes <- ggplot(data = top_5_lakes, aes(x = lake_id,y = ramu_count)) +
  geom_bar(stat = "identity", fill = "gold", alpha = .8, width = .4) +
  theme_minimal() +
  coord_flip() +
    labs(x = "",
         y = "Frogs Observed",
         title = "B") +
   theme(plot.title = element_text(size = 10,
                                  face = "bold",
        hjust = 0),
        text = element_text(size = 10),
        axis.title.y = element_text(size = 6)) 

```


```{r}
# Graph 3: combine both graphs to have 1 common figure to show mountain yellow-legged frog counts in different ways
graph_c <- (graph_life / graph_lakes) 

```

```{r, fig.cap= "**Figure 1. Mountain Yellow-legged Frog (RAMU) observations in the southern Sierra Nevadas from 1995-2002.** (**A**) Yearly observations of mountain yellow-legged frogs from 1995-2002 broken down by different life stage, (Adult, Subadult, Tadpole), excluding eggmmass stage. (**B**) Total frogs observed from 1995-2002 in the 5 lakes with the highest populations."}
graph_c
```

