---
title: "assignment_1: Part 1"
author: "Shelby Walsh"
date: "1/21/2021"
output: html_document
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(janitor)
library(here)
library(readxl)
library(ggplot2)
library(patchwork)
library(lubridate)
```

## Sierra Amphibian Analysis
```{r}
#read in xlsx data and clean
sierra_amp <- read_excel("sierra_amphibians.xlsx") %>% 
  clean_names() %>% 
  mutate(across(where(is.character), tolower)) 
```

# Graph 1: mountain yellow-legged frog (Rana muscosa)
```{r}
#modify table to get counts for mountain yellow-legged frog per year grouped by life stage (excluding eggmass)
mylf <- sierra_amp %>% 
  mutate(year = year(survey_date)) %>% 
  select(amphibian_species, amphibian_life_stage, amphibian_number, year) %>% 
  filter(amphibian_species == "ramu",
         amphibian_life_stage %in% c("tadpole", "subadult", "adult")) %>% 
  group_by(year, amphibian_life_stage) %>% 
  summarise(ramu_count = sum(amphibian_number))

lables <- c(adult = "Adult", subadult = "Subadult", tadpole = "Tadpole")

#need to change size, color, ledgend and title
graph_life <- ggplot(data = mylf, aes(x = year, y = ramu_count)) +
  geom_bar(stat = "identity", aes(fill = amphibian_life_stage, alpha = 1, width = .4), show.legend = FALSE) +
  scale_fill_brewer(palette = "YlOrRd") +
  theme_minimal()+
  facet_wrap(~amphibian_life_stage, scales = "free_y", 
             labeller = labeller(amphibian_life_stage = lables))+      
  labs(x = "",
       y = "Frog Count per Year",
         title = "A") +
   theme(plot.title = element_text(size = 10,
                                   face = "bold",
        hjust = 0)) +
  theme(text = element_text(size = 10),
        axis.title.y = element_text(size = 8),
        strip.text.x = element_text(size=8, face = "bold"))

graph_life
```

# Graph 2: 5 Lakes Observations
```{r}

lakes <- sierra_amp %>% 
  select(lake_id, amphibian_species, amphibian_life_stage, amphibian_number)%>%
  filter(amphibian_species == "ramu",
         amphibian_life_stage %in% c("subadult", "adult")) %>% 
  group_by(lake_id) %>% 
  summarise(ramu_count = sum(amphibian_number))

lakes$lake_id <- paste0('Lake ', lakes$lake_id, sep = ' ')

#factor reorder to get largest to smallest number of frogs
top_5_lakes <- lakes %>% 
  top_n(5) %>% 
  mutate(lake_id = fct_reorder(lake_id, ramu_count)) 

#plot frogs from top 5 lakes largest to smallest
 graph_lakes <- ggplot(data = top_5_lakes, aes(x = lake_id,y = ramu_count)) +
  geom_bar(stat = "identity", fill = "gold", alpha = .8, width = .4) +
  theme_minimal() +
  coord_flip() +
    labs(x = "",
         y = "Frog Count per Lake",
         title = "B") +
   theme(plot.title = element_text(size = 10,
                                  face = "bold",
        hjust = 0),
        text = element_text(size = 10),
        axis.title.y = element_text(size = 8)) 
 
  graph_lakes

```

## Part 3: Combine 2 graphs for 1 compound figure
```{r}
graph_c <- (graph_life / graph_lakes) 

graph_c
```

